#!/system/bin/sh

#if [ ! -f "/sdcard/DHD/wpx.ko" ]
#then
#	echo "Kernel module not found, please run check first!!!"
#else
	busybox insmod /sdcard/DHD/wpx.ko

	echo ""
	echo "If you get this error:"
	echo ""
	echo "insmod: init_module '/sdcard/DHD/wpx.ko' failed (Function not implemented)"
	echo ""
	echo "or"
	echo ""
	echo "insmod: can't insert '/sdcard/DHD/wpx.ko': Function not implemented"
	echo ""
	echo "This means the module worked ;)"
	echo ""

	busybox sleep 5

	busybox dd if=/sdcard/DHD/hboot_eng.nb0 of=/dev/block/mmcblk0p18
	busybox dd if=/dev/block/mmcblk0p18 of=/sdcard/DHD/hboot_check.nb0

	echo ""

	busybox md5sum /sdcard/DHD/hboot_check.nb0
	echo "df4fd77f44993eb05a4732210d2eddc6 << CORRECT MD5"
	busybox md5sum /sdcard/DHD/hboot_orig0.bin

	echo ""
	echo "If the first and second MD5 sums match, it went correct and you are safe to reboot!"
	echo "If the first and third MD5 sums match, it failed writing but this is NOT fatal and still safe to reboot!"
	echo ""
	echo "IF THE FIRST MD5 SUM DOES NOT MATCH EITHER SECOND OR THIRD"
	echo "DO NOT TURN OFF YOUR PHONE!!!"
	echo "IF YOU DO YOUR PHONE WILL BE BRICKED!!!"
	echo ""
	echo "But this should not happen, if it does happen seek help on the forums!"
	echo ""
	echo ""
	echo "If the flash went correct you can now reboot and install a custom recovery trough fastboot."
#fi
